### ISSUE TITLE
Correct use of BatlowW and BatlowK

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/cmcrameri#25]
As detailed in #24 by tobiscode, batlowW and batlowK are now acceptable as categorical colormaps

**Comment by tobiscode** [comment]
Hi,
I don't see the relevant commit, and after updating to v1.6 on PyPI, I still get the following error:
```
>>> from cmcrameri import cm
>>> cm.batlowS
<matplotlib.colors.ListedColormap object at 0x000002058EDA0B50>
>>> cm.batlowW
<matplotlib.colors.ListedColormap object at 0x000002058EDA0CD0>
>>> cm.batlowWS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cmcrameri.cm' has no attribute 'batlowWS'
>>> cm.batlowKS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cmcrameri.cm' has no attribute 'batlowKS'
```
Has the update not made it to PyPI yet?
Thanks!

**Comment by callumrollo** [comment]
Ah my mistake, I shouldn't have closed this! I've added the new categorical colourmaps including batlowKS and battlowWS in #28

**Comment by callumrollo** [comment]
Live on PyPI now with version 1.7 https://pypi.org/project/cmcrameri/#history

It has batlowWS and batlowKS

**Comment by tobiscode** [comment]
Works, thanks a lot!
